essential_styles = [
    "Photorealism",
    "Illustration / Cartoon",
    "Anime / Manga",
    "Abstract Art",
    "Pixel Art",
    "3D Render",
    "Line Art / Sketch",
    "Vector / Flat Design",
    "Chibi Sticker Art",
]

style_categories = {
    "Sticker Styles": [
        "Vibrant Illustrations & Cartoons",
        "Kawaii Style",
        "Chibi Sticker Art",
        "Bold & Simple Vector Graphics",
        "Minimalist Icons & Flat Design",
        "Text-Based Typography Stickers",
        "Hand-Lettered Stickers",
        "Motivational Quote Stickers",
        "Retro Phrase Stickers",
        "Abstract Pattern Stickers",
        "Mandalas & Psychedelic Patterns",
        "Geometric Pattern Stickers",
        "Pop Culture Fan Art (Sticker Format)",
        "Pixel Art Stickers",
        "Vaporwave / Synthwave Sticker Art",
        "80s/90s Retro Aesthetic Stickers",
        "Food Sticker Illustrations",
        "Cute Animal Stickers",
    ],
    "Anime & Manga Styles": [
        "Anime (General)",
        "Manga (Ink/Screen Tone)",
        "Chibi / Super Deformed (SD)",
        "Studio Ghibli Inspired",
        "Mecha Anime",
        "Dark Fantasy Anime",
        "Horror Anime / Guro",
        "Cyberpunk Anime",
        "Retro Anime (70s/80s/90s)",
        "Webtoon / Manhwa Style",
        "Magical Girl (Mahou Shoujo)",
        "Kemonomimi (Animal Features)",
        "Cel Shaded Anime",
    ],
    "Digital Art Styles": [
        "Photorealistic Digital",
        "3D Render",
        "Pixel Art",
        "Vector Art",
        "Digital Painting",
        "Flat Design",
        "Low Poly",
        "Synthwave / Outrun",
        "Vaporwave",
        "Isometric Digital Art",
        "Glitch Art",
        "Digital Collage",
        "Concept Art (Digital)",
        "Matte Painting (Digital)",
        "Procedural Art",
        "Neon / Holographic Aesthetic",
    ],
    "Traditional Art Mediums & Movements": [
        "Oil Painting",
        "Watercolor Painting",
        "Sketch / Drawing (Pencil/Charcoal/Pen)",
        "Line Art (Clean Ink)",
        "Impressionism",
        "Expressionism",
        "Baroque",
        "Renaissance Art",
        "Cubism",
        "Surrealism",
        "Abstract Art",
        "Realism (Traditional)",
        "Ukiyo-e (Japanese Woodblock)",
        "Pastel Art",
        "Ink Wash Painting (Sumi-e)",
        "Pointillism",
        "Fresco",
        "Stained Glass Art",
        "Etching / Engraving",
        "Tempera Painting",
        "Woodcut / Linocut",
        "Gothic Illuminated Manuscript",
        "Mosaic Art",
        "Art Nouveau",
        "Art Deco",
    ],
    "Modern, Fantasy & Stylized Aesthetics": [
        "Cartoon (Western Animation)",
        "Fantasy Art (General)",
        "Cyberpunk (General)",
        "Steampunk",
        "Dieselpunk",
        "Solarpunk",
        "Biopunk",
        "Gothic Art / Dark Academia",
        "Pop Art",
        "Graffiti / Street Art",
        "Futuristic / Sci-Fi (Non-Cyberpunk)",
        "Retro (General, e.g., 50s, 60s)",
        "Film Noir Style",
        "Minimalist Design",
        "Dreamcore / Weirdcore",
        "Fairycore / Cottagecore",
        "Light Academia",
        "Postmodern Art",
        "Mythological Art",
        "Witchcore / Arcane Aesthetic",
        "Afrofuturism",
    ],
}